# Generated by Django 4.1.6 on 2023-09-16 20:27

import bioinformatic.models.bioinformatic
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioinformaticAnalizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(blank=True, max_length=100, verbose_name='İşlem')),
                ('reading_file_format', models.CharField(blank=True, choices=[('abi', 'ABİ'), ('abi-trim', 'ABI-TRIM'), ('ace', 'ACE'), ('cif-atom', 'CIF-ATOM'), ('cif-seqres', 'CIF-SEQRES'), ('clustal', 'CLUSTAL'), ('embl', 'EMBL'), ('embl-cds', 'EMBL-CDS'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('genbank-cds', 'GENBANK (.genbank-cds) '), ('gck', 'GCK'), ('ig', 'IG'), ('imgt', 'IMGT'), ('nib', 'NIB'), ('nexus', 'NEXUS'), ('pdb-atom', 'PDB-ATOM'), ('pdb-seqres', 'PDB-SEQRES'), ('phd', 'PHD'), ('phylip', 'PHYLIP'), ('pir', 'PIR'), ('qual', 'QUAL'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('sff-trim', 'SFF-TRIM'), ('snapgene', 'SNAPGENE'), ('stockholm', 'STOCKHOLM'), ('swiss', 'SWISS'), ('tab', 'TAB'), ('qual', 'QUAL'), ('twobit', 'TWOBIT'), ('uniprot-xml', 'UNIPROT-XML'), ('xdna', 'XDNA')], max_length=100, verbose_name='Dosya Okuma Formatı')),
                ('writing_file_format', models.CharField(blank=True, choices=[('clustal', 'CLUSTAL'), ('embl', 'EMBL'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('imgt', 'IMGT'), ('nexus', 'NEXUS'), ('phd', 'PHD'), ('phylip', 'PHYLIP'), ('pir', 'PIR'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('stockholm', 'STOCKHOLM'), ('tab', 'TAB'), ('qual', 'QUAL'), ('xdna', 'XDNA')], max_length=100, verbose_name='Dosya Yazdırma Formatı')),
                ('molecule', models.CharField(blank=True, choices=[('', '------------'), ('DNA', 'DNA'), ('RNA', 'RNA'), ('protein', 'PROTEİN')], max_length=100, verbose_name='Molekül')),
                ('read_file', models.FileField(blank=True, help_text='Not : Max. dosya boyutu 5mb olmalıdır.', upload_to=bioinformatic.models.bioinformatic.read_file, verbose_name='Dosya')),
                ('trans_table', models.CharField(blank=True, choices=[('', '------------'), ('1', 'Standart Kod'), ('2', 'Omurgalı Mitokondri Kodu'), ('3', 'Maya Mitokondri Kodu'), ('4', 'Küf, Protozoon ve Kölenterat Mitokondri Kodu ve Mikoplazma/Spiroplasma Kodu'), ('5', 'Omurgasız Mitokondri Kodu'), ('6', 'Siliat, Dasikladas ve Heksamita Nükleer Kodu'), ('9', 'Ekinoderm ve Yassı Solucan Mitokondri Kodu'), ('10', 'Euplotid Nükleer Kodu'), ('11', 'Bakteriyel, Arkeal ve Bitki Plastid Kodu, prokaryotik virüsler'), ('12', 'Alternatif Maya Nükleer Kodu'), ('13', 'Ascidian Mitokondri Kodu'), ('14', 'Alternatif Yassı Solucan Mitokondri Kodu'), ('16', 'Klorofis Mitokondri Kodu'), ('21', 'Trematod Mitokondriyal Kodu'), ('22', 'Scenedesmus obliquus Mitokondri Kodu'), ('23', 'Thraustochytrium Mitokondri Kodu'), ('24', 'Rhabdopleuridae Mitokondri Kodu'), ('25', 'Aday Bölüm SR1 ve Gracilibacteria Kodu'), ('26', 'Pachysolen tannophilus Nükleer Kodu'), ('27', 'Karyorelict Nükleer Kodu'), ('28', 'Kondilostoma Nükleer Kodu'), ('29', 'Mezodinyum Nükleer Kodu'), ('30', 'Peritrich Nükleer Kodu'), ('31', 'Blastocrithidia Nükleer Kodu'), ('33', 'Cephalodiscidae Mitokondriyal UAA-Tyr Kodu')], max_length=100, verbose_name='Dönüşüm Tablosu')),
                ('to_stop', models.BooleanField(default=False, verbose_name='Stop kodonları dahil et.')),
                ('molecule_id', models.CharField(blank=True, max_length=100, verbose_name='İD')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Adı')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='TANIMLAMA')),
                ('organism', models.CharField(blank=True, max_length=100, null=True, verbose_name='ORGANİZMA')),
                ('taxonomy', models.CharField(blank=True, max_length=100, verbose_name='TAKSONOMİ')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='YAZAR')),
                ('keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anahtar Kelimeler')),
                ('strain', models.CharField(blank=True, max_length=100)),
                ('gene', models.CharField(blank=True, max_length=100)),
                ('select', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('seq', models.TextField(blank=True, verbose_name='SEKANS')),
                ('seq_len', models.IntegerField(blank=True, null=True, verbose_name='Sekans Uzunluğu')),
                ('gc', models.FloatField(blank=True, null=True, verbose_name='%GC')),
                ('pro_seq', models.TextField(blank=True, verbose_name='PROTEİN SEKANS')),
                ('pro_seq_len', models.IntegerField(blank=True, null=True, verbose_name='PROTEİN SEKANS UZUNLUĞU')),
                ('alignment', models.TextField(blank=True, verbose_name='Alignment')),
                ('alignment_file', models.FileField(blank=True, upload_to=bioinformatic.models.bioinformatic.alignment_file, verbose_name='Alignment Dosyası')),
                ('out_file_fasta', models.FileField(blank=True, upload_to='laboratory/file/fasta/', verbose_name='Sonuç Fasta')),
                ('out_file_genbank', models.FileField(blank=True, upload_to='laboratory/file/genbank/', verbose_name='Sonuç Genbank')),
                ('out_file_xml', models.FileField(blank=True, upload_to='laboratory/file/xml/', verbose_name='Sonuç XML')),
                ('out_file_tree', models.FileField(blank=True, upload_to='laboratory/file/tree/', verbose_name='Sonuç TREE')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laborant')),
            ],
            options={
                'verbose_name': 'Biyoinformatik Analiz',
                'verbose_name_plural': 'Biyoinformatik Analiz',
                'db_table': 'bioinformatic',
            },
        ),
        migrations.CreateModel(
            name='BioinformaticDatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(blank=True, max_length=100, verbose_name='Veri Tabanı Adı')),
                ('format', models.CharField(blank=True, choices=[('abi', 'ABİ'), ('abi-trim', 'ABI-TRIM'), ('ace', 'ACE'), ('cif-atom', 'CIF-ATOM'), ('cif-seqres', 'CIF-SEQRES'), ('clustal', 'CLUSTAL'), ('embl', 'EMBL'), ('embl-cds', 'EMBL-CDS'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('genbank-cds', 'GENBANK (.genbank-cds) '), ('gck', 'GCK'), ('ig', 'IG'), ('imgt', 'IMGT'), ('nib', 'NIB'), ('nexus', 'NEXUS'), ('pdb-atom', 'PDB-ATOM'), ('pdb-seqres', 'PDB-SEQRES'), ('phd', 'PHD'), ('phylip', 'PHYLIP'), ('pir', 'PIR'), ('qual', 'QUAL'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('sff-trim', 'SFF-TRIM'), ('snapgene', 'SNAPGENE'), ('stockholm', 'STOCKHOLM'), ('swiss', 'SWISS'), ('tab', 'TAB'), ('qual', 'QUAL'), ('twobit', 'TWOBIT'), ('uniprot-xml', 'UNIPROT-XML'), ('xdna', 'XDNA')], max_length=100, verbose_name='Format')),
                ('molecule', models.CharField(blank=True, choices=[('', '------------'), ('DNA', 'DNA'), ('RNA', 'RNA'), ('protein', 'PROTEİN')], max_length=100, verbose_name='Molekül')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen (Kullanıcı ADI)')),
            ],
            options={
                'verbose_name': 'Biyoinformatik Veri Tabanı',
                'verbose_name_plural': 'Biyoinformatik Veri Tabanı',
            },
        ),
        migrations.CreateModel(
            name='BiologicalResourcesDatabases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('url', models.URLField(verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Biyolojik Kaynaklar ve Veri Tabanları',
                'verbose_name_plural': 'Biyolojik Kaynaklar ve Veri Tabanları',
            },
        ),
        migrations.CreateModel(
            name='LabSlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laboratory/slide/')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('text', models.CharField(max_length=100, verbose_name='Alt Başlık:')),
                ('content', models.TextField(verbose_name='İçerik')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
                'db_table': 'bioinformatic_home',
            },
        ),
        migrations.CreateModel(
            name='Letter_Annotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='AD')),
                ('description', models.CharField(max_length=100, verbose_name='TANIM')),
                ('letter_annotations', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_annotations', to='bioinformatic.bioinformaticanalizmodel', verbose_name='letter_annotations')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='AD')),
                ('description', models.CharField(max_length=100, verbose_name='TANIM')),
                ('features', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bioinformatic.bioinformaticanalizmodel', verbose_name='Features')),
            ],
        ),
        migrations.CreateModel(
            name='DBXRefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='AD')),
                ('description', models.CharField(max_length=100, verbose_name='TANIM')),
                ('dbxRefs', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dbxrefs', to='bioinformatic.bioinformaticanalizmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CreateDatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('organism', models.CharField(blank=True, max_length=100)),
                ('taxonomy', models.CharField(blank=True, max_length=100)),
                ('annotations', models.CharField(blank=True, max_length=100)),
                ('letter_annotations', models.CharField(blank=True, max_length=100)),
                ('dbxrefs', models.CharField(blank=True, max_length=100)),
                ('features', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('sequence', models.TextField(blank=True)),
                ('record', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bioinformatic.bioinformaticdatabasemodel')),
            ],
            options={
                'verbose_name': 'Biyoinformatik Kayıt',
                'verbose_name_plural': 'Biyoinformatik Kayıt',
            },
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='AD')),
                ('description', models.CharField(max_length=100, verbose_name='TANIM')),
                ('annotations', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='bioinformatic.bioinformaticanalizmodel', verbose_name='Annotations')),
            ],
        ),
    ]
