# Generated by Django 4.1.6 on 2023-09-05 19:35

import bioinformatic.models.bioinformatic
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalResourcesDatabases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('url', models.URLField(verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Biyolojik Kaynaklar ve Veri Tabanları',
                'verbose_name_plural': 'Biyolojik Kaynaklar ve Veri Tabanları',
            },
        ),
        migrations.CreateModel(
            name='LabSlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laboratory/slide/')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('text', models.CharField(max_length=100, verbose_name='Alt Başlık:')),
                ('content', models.TextField(verbose_name='İçerik')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
                'db_table': 'bioinformatic_home',
            },
        ),
        migrations.CreateModel(
            name='BioinformaticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(blank=True, max_length=100, verbose_name='İşlem')),
                ('file_format', models.CharField(blank=True, choices=[('abi', 'ABİ'), ('abi-trim', 'ABI-TRIM'), ('ace', 'ACE'), ('cif-seqres', 'CIF-SEQRES'), ('cif-atom', 'CIF-ATOM'), ('embl', 'EMBL'), ('embl-cds', 'EMBL-CDS'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('genbank-cds', 'GENBANK (.genbank-cds) '), ('gck', 'GCK'), ('imgt', 'IMGT'), ('ig', 'IG'), ('nib', 'NIB'), ('pdb-atom', 'PDB-ATOM'), ('pdb-seqres', 'PDB-SEQRES'), ('phd', 'PHD'), ('pir', 'PIR'), ('qual', 'QUAL'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('snapgene', 'SNAPGENE'), ('sff-trim', 'SFF-TRIM'), ('swiss', 'SWISS'), ('tab', 'TAB'), ('twobit', 'TWOBIT'), ('uniprot-xml', 'UNIPROT-XML'), ('xdna', 'XDNA')], max_length=100, verbose_name='Dosya Formatı')),
                ('molecule', models.CharField(blank=True, choices=[('', '------------'), ('DNA', 'DNA'), ('RNA', 'RNA'), ('protein', 'PROTEİN')], max_length=100, verbose_name='Molekül')),
                ('read_file', models.FileField(blank=True, help_text='Not : Max. dosya boyutu 5mb olmalıdır.', upload_to=bioinformatic.models.bioinformatic.read_file, verbose_name='Dosya')),
                ('trans_table', models.CharField(blank=True, choices=[('', '------------'), ('1', 'Standart Kod'), ('2', 'Omurgalı Mitokondri Kodu'), ('3', 'Maya Mitokondri Kodu'), ('4', 'Küf, Protozoon ve Kölenterat Mitokondri Kodu ve Mikoplazma/Spiroplasma Kodu'), ('5', 'Omurgasız Mitokondri Kodu'), ('6', 'Siliat, Dasikladas ve Heksamita Nükleer Kodu'), ('9', 'Ekinoderm ve Yassı Solucan Mitokondri Kodu'), ('10', 'Euplotid Nükleer Kodu'), ('11', 'Bakteriyel, Arkeal ve Bitki Plastid Kodu, prokaryotik virüsler'), ('12', 'Alternatif Maya Nükleer Kodu'), ('13', 'Ascidian Mitokondri Kodu'), ('14', 'Alternatif Yassı Solucan Mitokondri Kodu'), ('16', 'Klorofis Mitokondri Kodu'), ('21', 'Trematod Mitokondriyal Kodu'), ('22', 'Scenedesmus obliquus Mitokondri Kodu'), ('23', 'Thraustochytrium Mitokondri Kodu'), ('24', 'Rhabdopleuridae Mitokondri Kodu'), ('25', 'Aday Bölüm SR1 ve Gracilibacteria Kodu'), ('26', 'Pachysolen tannophilus Nükleer Kodu'), ('27', 'Karyorelict Nükleer Kodu'), ('28', 'Kondilostoma Nükleer Kodu'), ('29', 'Mezodinyum Nükleer Kodu'), ('30', 'Peritrich Nükleer Kodu'), ('31', 'Blastocrithidia Nükleer Kodu'), ('33', 'Cephalodiscidae Mitokondriyal UAA-Tyr Kodu')], max_length=100, verbose_name='Dönüşüm Tablosu')),
                ('to_stop', models.BooleanField(default=False, verbose_name='Stop kodonları dahil edilsin')),
                ('molecule_id', models.CharField(blank=True, max_length=100, verbose_name='İD')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Tanım')),
                ('annotations', models.CharField(blank=True, max_length=100, verbose_name='Anotasyon')),
                ('features', models.CharField(blank=True, max_length=100, verbose_name='Özellikler')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yazar:')),
                ('keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anahtar Kelimeler:')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('seq', models.TextField(blank=True, verbose_name='Sekans')),
                ('seq_len', models.IntegerField(blank=True, null=True, verbose_name='Sekans Uzunluğu')),
                ('gc', models.FloatField(blank=True, null=True, verbose_name='%GC')),
                ('pro_seq', models.TextField(blank=True, verbose_name='PROTEİN Sekans')),
                ('pro_seq_len', models.IntegerField(blank=True, verbose_name='PROTEİN Sekans Uzunluğu')),
                ('ex_seq', models.TextField(blank=True, verbose_name='Extra Sekans')),
                ('out_file_fasta', models.FileField(blank=True, upload_to='laboratory/file/fasta/', verbose_name='Sonuç Fasta')),
                ('out_file_genbank', models.FileField(blank=True, upload_to='laboratory/file/genbank/', verbose_name='Sonuç Genbank')),
                ('out_file_xml', models.FileField(blank=True, upload_to='laboratory/file/xml/', verbose_name='Sonuç XML')),
                ('out_file_tree', models.FileField(blank=True, upload_to='laboratory/file/tree/', verbose_name='Sonuç TREE')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laborant')),
            ],
            options={
                'verbose_name': 'BİYOİNFORMATİK',
                'verbose_name_plural': 'BİYOİNFORMATİK',
                'db_table': 'bioinformatic',
            },
        ),
    ]
