# Generated by Django 4.1.6 on 2023-09-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
