# Generated by Django 4.1.6 on 2023-09-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbxrefs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='features',
            name='description',
        ),
    ]
