# Generated by Django 5.0.6 on 2024-06-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesearchmodel',
            options={'verbose_name': 'Güncel Makale Arama', 'verbose_name_plural': 'Güncel Makale Arama'},
        ),
        migrations.RemoveField(
            model_name='articlesearchmodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='articlesearchmodel',
            name='article_id',
            field=models.CharField(max_length=100, verbose_name='Makale ID'),
        ),
        migrations.AlterField(
            model_name='articlesearchmodel',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Başlık'),
        ),
    ]
