# Generated by Django 4.1.6 on 2023-09-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='alignment_file',
            field=models.FileField(blank=True, upload_to='laboratory/file/alignment/', verbose_name='Alignment Dosyası'),
        ),
    ]
