# Generated by Django 4.1.6 on 2023-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticmodel',
            name='pro_seq_len',
            field=models.IntegerField(blank=True, null=True, verbose_name='PROTEİN Sekans Uzunluğu'),
        ),
    ]
