# Generated by Django 5.0.6 on 2024-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_alter_articlesearchmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesearchmodel',
            name='pub_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Date Publication'),
        ),
    ]
