# Generated by Django 4.1.6 on 2023-09-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_alter_bioinformaticmodel_pro_seq_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticmodel',
            name='to_stop',
            field=models.BooleanField(default=False, verbose_name='Stop kodonları dahil et.'),
        ),
    ]
