# Generated by Django 4.1.6 on 2023-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_remove_dbxrefs_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbxrefs',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='dbxrefs'),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Features'),
        ),
    ]
