# Generated by Django 4.1.6 on 2023-09-14 07:19

import bioinformatic.models.bioinformatic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0002_bioinformaticanalizmodel_alignment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioinformaticanalizmodel',
            name='file_format',
        ),
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adı'),
        ),
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='reading_file_format',
            field=models.CharField(blank=True, choices=[('abi', 'ABİ'), ('abi-trim', 'ABI-TRIM'), ('ace', 'ACE'), ('cif-atom', 'CIF-ATOM'), ('cif-seqres', 'CIF-SEQRES'), ('clustal', 'CLUSTAL'), ('embl', 'EMBL'), ('embl-cds', 'EMBL-CDS'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('genbank-cds', 'GENBANK (.genbank-cds) '), ('gck', 'GCK'), ('ig', 'IG'), ('imgt', 'IMGT'), ('nib', 'NIB'), ('nexus', 'NEXUS'), ('pdb-atom', 'PDB-ATOM'), ('pdb-seqres', 'PDB-SEQRES'), ('phd', 'PHD'), ('phylip', 'PHYLIP'), ('pir', 'PIR'), ('qual', 'QUAL'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('sff-trim', 'SFF-TRIM'), ('snapgene', 'SNAPGENE'), ('stockholm', 'STOCKHOLM'), ('swiss', 'SWISS'), ('tab', 'TAB'), ('qual', 'QUAL'), ('twobit', 'TWOBIT'), ('uniprot-xml', 'UNIPROT-XML'), ('xdna', 'XDNA')], max_length=100, verbose_name='Dosya Formatı'),
        ),
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='writing_file_format',
            field=models.CharField(blank=True, choices=[('clustal', 'CLUSTAL'), ('embl', 'EMBL'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('imgt', 'IMGT'), ('nexus', 'NEXUS'), ('phd', 'PHD'), ('phylip', 'PHYLIP'), ('pir', 'PIR'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('stockholm', 'STOCKHOLM'), ('tab', 'TAB'), ('qual', 'QUAL'), ('xdna', 'XDNA')], max_length=100, verbose_name='Dosya Formatı'),
        ),
        migrations.AlterField(
            model_name='bioinformaticanalizmodel',
            name='alignment_file',
            field=models.FileField(blank=True, upload_to=bioinformatic.models.bioinformatic.alignment_file, verbose_name='Alignment Dosyası'),
        ),
        migrations.AlterField(
            model_name='bioinformaticdatabasemodel',
            name='format',
            field=models.CharField(blank=True, choices=[('abi', 'ABİ'), ('abi-trim', 'ABI-TRIM'), ('ace', 'ACE'), ('cif-atom', 'CIF-ATOM'), ('cif-seqres', 'CIF-SEQRES'), ('clustal', 'CLUSTAL'), ('embl', 'EMBL'), ('embl-cds', 'EMBL-CDS'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('genbank-cds', 'GENBANK (.genbank-cds) '), ('gck', 'GCK'), ('ig', 'IG'), ('imgt', 'IMGT'), ('nib', 'NIB'), ('nexus', 'NEXUS'), ('pdb-atom', 'PDB-ATOM'), ('pdb-seqres', 'PDB-SEQRES'), ('phd', 'PHD'), ('phylip', 'PHYLIP'), ('pir', 'PIR'), ('qual', 'QUAL'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('sff-trim', 'SFF-TRIM'), ('snapgene', 'SNAPGENE'), ('stockholm', 'STOCKHOLM'), ('swiss', 'SWISS'), ('tab', 'TAB'), ('qual', 'QUAL'), ('twobit', 'TWOBIT'), ('uniprot-xml', 'UNIPROT-XML'), ('xdna', 'XDNA')], max_length=100, verbose_name='Format'),
        ),
    ]
