# Generated by Django 4.1.6 on 2023-09-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0003_alter_dbxrefs_name_alter_features_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter_annotations',
            name='letter_annotations',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_annotations', to='bioinformatic.bioinformaticanalizmodel', verbose_name='Letter_annotations'),
        ),
    ]
