# Generated by Django 4.1.6 on 2023-09-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0003_alter_bioinformaticmodel_to_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticmodel',
            name='organism',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organizma'),
        ),
    ]
