# Generated by Django 5.0.6 on 2024-06-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0003_articlesearchmodel_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesearchmodel',
            name='pub_date',
        ),
    ]
