# Generated by Django 4.1.6 on 2023-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0004_bioinformaticmodel_organism'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticmodel',
            name='taxonomy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Taksonomi'),
        ),
    ]
