# Generated by Django 4.1.6 on 2023-09-09 03:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioinformatic', '0005_bioinformaticmodel_taxonomy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BioinformaticModel',
            new_name='BioinformaticAnalizModel',
        ),
        migrations.AlterModelOptions(
            name='bioinformaticanalizmodel',
            options={'verbose_name': 'Biyoinformatik Analiz', 'verbose_name_plural': 'Biyoinformatik Analiz'},
        ),
    ]
