# Generated by Django 4.1.6 on 2023-09-09 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioinformatic', '0006_rename_bioinformaticmodel_bioinformaticanalizmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioinformaticDatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('abi', 'ABİ'), ('abi-trim', 'ABI-TRIM'), ('ace', 'ACE'), ('cif-seqres', 'CIF-SEQRES'), ('cif-atom', 'CIF-ATOM'), ('embl', 'EMBL'), ('embl-cds', 'EMBL-CDS'), ('fasta', 'FASTA'), ('fastq', 'FASTQ'), ('fasta-2line', 'FASTA-2LINE'), ('fastq-sanger', 'FASTQ-SANGER'), ('fastq-solexa', 'FASTQ-SOLEXA'), ('fastq-illumina', 'FASTQ-ILLUMINA'), ('gb', 'GENBANK (.gb) '), ('genbank', 'GENBANK (.genbank)'), ('genbank-cds', 'GENBANK (.genbank-cds) '), ('gck', 'GCK'), ('imgt', 'IMGT'), ('ig', 'IG'), ('nib', 'NIB'), ('pdb-atom', 'PDB-ATOM'), ('pdb-seqres', 'PDB-SEQRES'), ('phd', 'PHD'), ('pir', 'PIR'), ('qual', 'QUAL'), ('seqxml', 'SEQXML'), ('sff', 'SFF'), ('snapgene', 'SNAPGENE'), ('sff-trim', 'SFF-TRIM'), ('swiss', 'SWISS'), ('tab', 'TAB'), ('twobit', 'TWOBIT'), ('uniprot-xml', 'UNIPROT-XML'), ('xdna', 'XDNA')], max_length=100, verbose_name='Format')),
                ('molecule', models.CharField(blank=True, choices=[('', '------------'), ('DNA', 'DNA'), ('RNA', 'RNA'), ('protein', 'PROTEİN')], max_length=100, verbose_name='Molekül')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen (Kullanıcı ADI)')),
            ],
            options={
                'verbose_name': 'Biyoinformatik Veri Tabanı',
                'verbose_name_plural': 'Biyoinformatik Veri Tabanı',
            },
        ),
        migrations.CreateModel(
            name='CreateDatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('organism', models.CharField(blank=True, max_length=100)),
                ('taxonomy', models.CharField(blank=True, max_length=100)),
                ('annotations', models.CharField(blank=True, max_length=100)),
                ('letter_annotations', models.CharField(blank=True, max_length=100)),
                ('dbxrefs', models.CharField(blank=True, max_length=100)),
                ('features', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('sequence', models.TextField(blank=True)),
                ('record', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bioinformatic.bioinformaticdatabasemodel')),
            ],
            options={
                'verbose_name': 'Biyoinformatik Kayıt',
                'verbose_name_plural': 'Biyoinformatik Kayıt',
            },
        ),
    ]
