# Generated by Django 4.1.6 on 2023-09-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0006_fileextramodel_remove_dbxrefs_dbxrefs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='accession',
            field=models.CharField(blank=True, max_length=100, verbose_name='accession'),
        ),
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='dbxrefs',
            field=models.CharField(blank=True, max_length=100, verbose_name='dbxrefs'),
        ),
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='source'),
        ),
        migrations.DeleteModel(
            name='FileExtraModel',
        ),
    ]
