# Generated by Django 4.1.6 on 2023-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0007_bioinformaticdatabasemodel_createdatabasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticdatabasemodel',
            name='db_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Veri Tabanı Adı'),
        ),
    ]
