# Generated by Django 4.1.6 on 2023-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0008_bioinformaticdatabasemodel_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='db_xrefs',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
