# Generated by Django 4.1.6 on 2023-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0009_bioinformaticanalizmodel_db_xrefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='gene',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='strain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
