# Generated by Django 4.1.6 on 2023-09-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0010_bioinformaticanalizmodel_gene_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticanalizmodel',
            name='organism',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organizma'),
        ),
    ]
