# Generated by Django 4.1.6 on 2023-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0011_alter_bioinformaticanalizmodel_organism'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
