# Generated by Django 4.1.6 on 2023-09-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0012_bioinformaticanalizmodel_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticanalizmodel',
            name='annotations',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Anotasyon'),
        ),
        migrations.AlterField(
            model_name='bioinformaticanalizmodel',
            name='features',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Özellikler'),
        ),
    ]
