# Generated by Django 4.1.6 on 2023-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0013_alter_bioinformaticanalizmodel_annotations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticanalizmodel',
            name='features',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Özellikler'),
        ),
    ]
