# Generated by Django 4.1.6 on 2023-09-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatic', '0014_alter_bioinformaticanalizmodel_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioinformaticanalizmodel',
            name='ex_seq',
        ),
        migrations.AddField(
            model_name='bioinformaticanalizmodel',
            name='alignment',
            field=models.TextField(blank=True, verbose_name='Alignment'),
        ),
    ]
