# Generated by Django 4.1.6 on 2023-09-20 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Bildirim türü')),
                ('title', models.CharField(max_length=100, verbose_name='Bildirim başlığı')),
                ('text', models.TextField(blank=True, verbose_name='Bildirim içeriği')),
                ('url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'Bildrim',
                'verbose_name_plural': 'Bildrimler',
                'db_table': 'notifications',
            },
        ),
    ]
