# Generated by Django 4.1.6 on 2023-09-20 17:25

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=150, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, upload_to=accounts.models.avatar, verbose_name='Avatar:')),
                ('gender', models.CharField(blank=True, choices=[('', '------'), ('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtmek istemiyorum', 'Belirtmek istemiyorum')], default='', max_length=30, verbose_name='Cinsiyet')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Yaşadığı şehir')),
                ('about', models.TextField(blank=True, verbose_name='Hakkımda')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='Meslek')),
                ('phone', models.CharField(blank=True, max_length=130, null=True, unique=True, verbose_name='Telefon')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi:')),
                ('skills', models.CharField(blank=True, max_length=2000, verbose_name='Yetenekler')),
                ('web_site', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('language', models.CharField(blank=True, help_text='ingilizce', max_length=2000, verbose_name='Bildiğiniz Diller')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Katılma Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(help_text='Facebook', max_length=100, verbose_name='Sosyal Medya Adı')),
                ('url', models.URLField(max_length=100, verbose_name='Sosyal Medya Url Adresi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social', to='accounts.profile', verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Bilgileri',
                'verbose_name_plural': 'Sosyal Medya Bilgileri',
                'db_table': 'profile_social',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Konu:')),
                ('content', models.TextField(verbose_name='Mesaj')),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_report', models.BooleanField(default=False, verbose_name='Kötüye kullanım')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı: ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gönderen', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Mesajlar',
                'verbose_name_plural': 'Mesajlar',
                'db_table': 'contact',
                'ordering': ['-created'],
            },
        ),
    ]
