# Generated by Django 4.1.4 on 2022-12-26 19:55

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(help_text='Facebook', max_length=100, unique=True, verbose_name='Sosyal Medya Adı')),
                ('url', models.URLField(max_length=100, verbose_name='Sosyal Medya Url Adresi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Bilgileri',
                'verbose_name_plural': 'Sosyal Medya Bilgileri',
                'db_table': 'profile_social',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=150, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cover', models.ImageField(blank=True, upload_to=accounts.models.cover, verbose_name='Kapak Fotosu:')),
                ('avatar', models.ImageField(blank=True, upload_to=accounts.models.avatar, verbose_name='Avatar:')),
                ('gender', models.CharField(blank=True, choices=[('', '------'), ('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtmek istemiyorum', 'Belirtmek istemiyorum')], default='', max_length=30, verbose_name='Cinsiyet')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Yaşadığı şehir')),
                ('about', models.TextField(blank=True, verbose_name='Hakkımda')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='Meslek')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Telefon')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi:')),
                ('skils', models.CharField(blank=True, max_length=200, verbose_name='Yetenekler')),
                ('language', models.CharField(blank=True, help_text='ingilizce', max_length=200, verbose_name='Bildiğiniz Diller')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Katılma Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(help_text='Mühendis', max_length=100, verbose_name='Meslek')),
                ('department', models.CharField(help_text='Gıda Mühendisi', max_length=100, verbose_name='Pozisyon')),
                ('location', models.CharField(help_text='Sabancı Holding', max_length=100, verbose_name='İş yeri adı')),
                ('start', models.CharField(help_text='2010', max_length=100, verbose_name='Başlangıç yılı')),
                ('explain', models.TextField(blank=True, verbose_name='Açıklama:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'İş Bilgileri',
                'verbose_name_plural': 'İş Bilgileri',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(help_text='Üniversite', max_length=100, verbose_name='Okul Türü')),
                ('school_name', models.CharField(help_text='Akdeniz Üniversitesi', max_length=100, verbose_name='Okul')),
                ('start', models.CharField(help_text='2010', max_length=100, verbose_name='Başlangıç yılı')),
                ('finish', models.CharField(help_text='2014', max_length=100, verbose_name='Bitiş yılı:')),
                ('explain', models.TextField(blank=True, verbose_name='Açıklama:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edu', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'Eğitim Bilgileri',
                'verbose_name_plural': 'Eğitim Bilgileri',
                'db_table': 'education',
            },
        ),
    ]
