# Generated by Django 3.2.16 on 2023-08-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.BooleanField(default=False, verbose_name='Takım'),
        ),
    ]
