# Generated by Django 3.2.16 on 2023-08-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
    ]
