# Generated by Django 4.1.4 on 2023-01-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_job_user_delete_education_delete_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='email',
            new_name='contact_email',
        ),
    ]
