# Generated by Django 4.1.4 on 2023-01-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_email_contactmodel_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Iletisim', 'verbose_name_plural': 'Iletisim'},
        ),
        migrations.AlterModelTable(
            name='contactmodel',
            table='contact',
        ),
    ]
