# Generated by Django 3.2.16 on 2023-08-27 19:18

import autoslug.fields
import blog.models
import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/posts/about/')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Hakkımızda')),
            ],
        ),
        migrations.CreateModel(
            name='BlogContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Blog İletişim',
                'verbose_name_plural': 'Blog İletişim',
                'db_table': 'blog_contact_form_model',
            },
        ),
        migrations.CreateModel(
            name='BlogContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_url', models.TextField(verbose_name='Google map url')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('explain', models.TextField(verbose_name='Açıklama')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('telephone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email adresimiz')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'blog_contact',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/category/', verbose_name='Kategori Fotosu:')),
                ('title', models.CharField(max_length=100, verbose_name='Kategori:')),
                ('explain', ckeditor.fields.RichTextField(verbose_name='Kategori Tanımı:')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlama Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'abone',
                'verbose_name_plural': 'aboneler',
                'db_table': 'subscribe',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to=blog.models.cover_upload_to, verbose_name='Gönderi Fotosu:')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık:')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='İçerik')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Etiketler')),
                ('extra_image1', models.ImageField(blank=True, upload_to=blog.models.extra_img_upload_to, verbose_name='Slayt1')),
                ('extra_image2', models.ImageField(blank=True, upload_to=blog.models.extra_img_upload_to, verbose_name='Slayt2')),
                ('extra_image3', models.ImageField(blank=True, upload_to=blog.models.extra_img_upload_to, verbose_name='Slayt3')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.CharField(choices=[('DF', 'Taslak'), ('PB', 'Yayınla')], default='DF', max_length=2, verbose_name='Yayınlanma Durumu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.category', verbose_name='Kategori')),
                ('dislike', models.ManyToManyField(blank=True, related_name='post_dislike', to=settings.AUTH_USER_MODEL, verbose_name='Beğenmedim')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL, verbose_name='Beğendim')),
            ],
            options={
                'verbose_name': 'Gönderi',
                'verbose_name_plural': 'Gönderi',
                'db_table': 'posts',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Yorum Yap:')),
                ('status', models.CharField(choices=[('okundu', 'Okundu'), ('okunmadı', 'okunmadı')], default='okunmadı', max_length=30, verbose_name='Okunma Durumu')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlama Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Yazan:')),
                ('dislike', models.ManyToManyField(blank=True, related_name='comment_dislike', to=settings.AUTH_USER_MODEL, verbose_name='Beğenmedim')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Beğendim')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.posts', verbose_name='Gönderi:')),
                ('report', models.ManyToManyField(blank=True, related_name='comment_report', to=settings.AUTH_USER_MODEL, verbose_name='Kötüye Kullanım')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'comments',
            },
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['created'], name='posts_created_3fb39c_idx'),
        ),
    ]
