# Generated by Django 3.2.16 on 2023-08-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogContact',
            new_name='BlogContactFormModel',
        ),
        migrations.RenameModel(
            old_name='About',
            new_name='BlogContactModel',
        ),
        migrations.AlterModelOptions(
            name='blogcontactmodel',
            options={'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim'},
        ),
        migrations.AlterModelTable(
            name='blogcontactformmodel',
            table='blog_contact_form_model',
        ),
        migrations.AlterModelTable(
            name='blogcontactmodel',
            table='blog_contact',
        ),
    ]
