# Generated by Django 4.1.4 on 2022-12-17 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='comment_dislike', to=settings.AUTH_USER_MODEL, verbose_name='Beğenmedim'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Beğendim'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='report',
            field=models.ManyToManyField(blank=True, related_name='comment_report', to=settings.AUTH_USER_MODEL, verbose_name='Kötüye Kullanım'),
        ),
    ]
