# Generated by Django 4.1.4 on 2022-12-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_dislike_alter_comments_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('okundu', 'Okundu'), ('okunmadı', 'okunmadı')], default='okunmadı', max_length=30, verbose_name='Okunma Durumu'),
        ),
    ]
