# Generated by Django 3.2.16 on 2023-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230822_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/posts/about/')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Hakkımızda')),
            ],
        ),
    ]
