# Generated by Django 4.1.4 on 2022-12-17 06:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Yorum Yap:'),
        ),
    ]
